*** empty log message ***

diff --git a/ltmain.sh.in b/ltmain.sh.in
--- a/ltmain.sh.in
+++ b/ltmain.sh.in
@@ -269,6 +269,8 @@ if test -z "$show_help"; then
     args="$cc"
     compile_command="$cc"
     finalize_command="$cc"
+    compile_shlibpath=
+    finalize_shlibpath=
     deplibs=
     install_libdir=
     libobjs=
@@ -290,14 +292,24 @@ if test -z "$show_help"; then
 #      suffix=
 #    fi
 
+    # We need to know -static, to get the right output filenames.
+    case " $@ " in
+    *" -static "*) build_libtool_libs=no ;;
+    esac
+
     for arg
     do
       # If the previous option needs an argument, assign it.
       if test -n "$prev"; then
 	case "$prev" in
 	output)
-	  compile_command="$compile_command $objdir/$arg"
-	  finalize_command="$finalize_command $objdir/$arg"T
+	  if test "$build_libtool_libs" = yes; then
+	    compile_command="$compile_command $objdir/$arg"
+	    finalize_command="$finalize_command $objdir/$arg"T
+	  else
+	    compile_command="$compile_command $arg"
+	    finalize_command="$finalize_command $arg"
+	  fi
 	  args="$args $arg"
 	  ;;
 	esac
@@ -308,9 +320,8 @@ if test -z "$show_help"; then
 	continue
       fi
 
-      # The finalize and compile arguments.
-      farg="$arg"
-      carg="$arg"
+      args="$args $arg"
+      prevarg="$arg"
 
       case "$arg" in
       -L*)
@@ -330,13 +341,15 @@ if test -z "$show_help"; then
 
       -o) prev=output ;;
 
-      -rpath) prev=install_libdir carg= farg= ;;
+      -rpath)
+	prev=install_libdir
+	continue
+	;;
 
       -static)
-	build_libtool_libs=no
 	link_static="`eval echo \"$link_static_flag\"`"
-	carg="$link_static"
-	farg=
+	compile_command="$compile_command $link_static"
+	continue
 	;;
 
       -version-file)
@@ -345,7 +358,10 @@ if test -z "$show_help"; then
 	exit 1
 	;;
 
-      -version-info) prev=vinfo carg= farg= ;;
+      -version-info)
+	prev=vinfo
+	continue
+	;;
 
       -*) cc="$cc $arg" ;; # Some other compiler flag.
 
@@ -361,16 +377,47 @@ if test -z "$show_help"; then
 
       *.la)
 	# A libtool-controlled library.
+
+	libdir=
+	library_names=
+	old_library=
+
+	# Check to see that this really is a libtool archive.
+	if egrep "^# Generated by $PROGRAM" $arg >/dev/null 2>&1; then :
+	else
+	  echo "$progname: \`$arg' is not a valid libtool archive" 1>&2
+	  exit 1
+	fi
+
+	# If there is no directory component, then add one.
+	case "$arg" in
+	*/*) . $arg ;;
+	*) . ./$arg ;;
+	esac
+
+	if test -z "$libdir"; then
+	  echo "$progname: \`$arg' contains no -rpath information" 1>&2
+	  exit 1
+	fi
+
+	# Get the name of the link library.
+	linklib=
+	for linklib in $library_names; do
+	  :
+	done
+
+	# Find the relevant object directory and library name.
+	name=`echo "$arg" | sed 's%^.*/%%; s/\.la$//; s/^lib//'`
 	dir=`echo "$arg" | sed 's%/[^/]*$%%'`
-	test "$dir" = "$arg" && dir=.
-	file=`echo "$arg" | sed 's%^.*/%%'`
+	if test "$dir" = "$arg"; then
+	  dir="$objdir"
+	else
+	  dir="$dir/$objdir"
+	fi
 
 	link_against_libtool_libs="$link_against_libtool_libs $arg"
-	if test "$build_libtool_libs" = yes; then
-	  # Specify the library as -lNAME.
-	  carg="-l`echo "$file" | sed 's/lib\(..*\)\.la$/\1/'`"
-	  farg="$carg"
 
+	if test "$build_libtool_libs" = yes; then
 	  if test -n "$shlibpath_var"; then
 	    # Make sure the rpath contains only unique directories.
 	    case "$temp_rpath " in
@@ -379,50 +426,70 @@ if test -z "$show_help"; then
 	    esac
 	  fi
 
-	  # Check to see that this really is a libtool archive.
-	  if egrep "^# Generated by $PROGRAM" $arg >/dev/null 2>&1; then :
-	  else
-	    echo "$progname: \`$arg' is not a valid libtool archive" 1>&2
+	  if test -z "$linklib"; then
+	    echo "$progname: cannot find name of link library for \`$arg'" 1>&2
 	    exit 1
 	  fi
 
-	  libdir=
-	  . $dir/$file
-
-	  if test -z "$libdir"; then
-	    echo "$progname: \`$arg' contains no -rpath information" 1>&2
-	    exit 1
+	  if test -n "$hardcode_libdir_flag"; then
+	    tmp=`eval echo \"$hardcode_libdir_flag\"`
+	    compile_command="$compile_command $tmp"
+	    finalize_command="$finalize_command $tmp"
 	  fi
 
-	  if test -n "$link_rpath_flag"; then
-	    carg="`eval echo \"$link_rpath_flag\"` $carg"
-	    farg="$carg"
-	  fi
+	  case "$hardcode_action" in
+	  rpath)
+	    if test "$hardcode_direct" = no; then
+	      compile_command="$compile_command $dir/$linklib"
+	    elif test "$hardcode_minus_L" = no; then
+	      compile_command="$compile_command -L$dir -l$name"
+	    elif test "$hardcode_shlibpath_var" = no; then
+	      compile_shlibpath="$compile_shlibpath$dir:"
+	      compile_command="$compile_command -l$name"
+	    fi
+	    ;;
 
-	  if test "$hardcode_minus_L" != yes; then
-	    # Just give the right -L directory flag.
-	    carg="-L$dir/$objdir $carg"
-
-	  elif test "$hardcode_shlibpath_var" != no; then
-	    # Give an absolute path to the library.
+	  relink)
+	    # We need an absolute path.
 	    case "$dir" in
-	    /*) absdir="$dir" ;;
+	    /*) ;;
 	    *)
-	      absdir=`cd $dir && pwd`
+	      absdir=`cd "$dir" && pwd`
 	      if test -z "$absdir"; then
-	        echo "$progname: cannot determine absolute pathname of \`$dir'" 1>&2
+		echo "$progname: cannot determine absolute directory name of \`$dir'" 1>&2
 		exit 1
 	      fi
-      	      ;;
-            esac
-            carg="-L$absdir/$objdir $carg"
-            farg="-L$libdir $farg"
-          fi
+	      dir="$absdir"
+	      ;;
+	    esac
+
+	    if test "$hardcode_direct" = yes; then
+	      compile_command="$compile_command $dir/$linklib"
+	    elif test "$hardcode_minus_L" = yes; then
+	      compile_command="$compile_command -L$dir -l$name"
+	    elif test "$hardcode_shlibpath_var" = yes; then
+	      compile_shlibpath="$compile_shlibpath$dir:"
+	      compile_command="$compile_command -l$name"
+	    fi
+	    ;;
+	  esac
+
+	  # Finalize command for both is simple: just hardcode it.
+	  if test "$hardcode_direct" = yes; then
+	    finalize_command="$finalize_command $libdir/$linklib"
+	  elif test "$hardcode_minus_L" = no; then
+	    finalize_command="$finalize_command -L$libdir -l$name"
+	  elif test "$hardcode_shlibpath_var" = no; then
+	    finalize_shlibpath="$finalize_shlibpath$libdir:"
+	    finalize_command="$finalize_command -l$name"
+	  fi
         else
           # Transform directly to old archives if we don't build new libraries.
-          carg="$dir/$objdir/`echo "$file" | sed 's/\.la$/.a/'`"
-          farg="$carg"
+	  test -z "$old_library" && old_library="$linklib"
+          compile_command="$compile_command $dir/$old_library"
+	  finalize_command="$finalize_command $dir/$old_library"
         fi
+	continue
 	;;
 
       *)
@@ -432,11 +499,8 @@ if test -z "$show_help"; then
 	;;
       esac
 
-      args="$args $arg"
-
-      compile_command="$compile_command $carg"
-      finalize_command="$finalize_command $farg"
-      prevarg="$arg"
+      compile_command="$compile_command $arg"
+      finalize_command="$finalize_command $arg"
     done
 
     if test -n "$prev"; then
@@ -725,7 +789,6 @@ if test -z "$show_help"; then
 
       if test -z "$link_against_libtool_libs" || test "$build_libtool_libs" != yes; then
 	# We have no uninstalled library dependencies, so finalize right now.
-	compile_command=`echo "$compile_command" | sed "s%-o $objdir/%-o %"`
 	$show "$compile_command"
 	$run $compile_command
 	status=$?
@@ -734,8 +797,8 @@ if test -z "$show_help"; then
 	if test $status -ne 0 && test -n "$link_static"; then
 	  echo "$progname: cannot link \`$output' statically; retrying semi-dynamically" 1>&2
 	  compile_command=`echo "$compile_command " | sed "s% $link_static % %;s/ $//"`
-	  $show "$compile_command"
-	  $run $compile_command
+	  $show "$finalize_command"
+	  $run $finalize_command
 	  status=$?
 	fi
 	exit $status
@@ -755,44 +818,36 @@ if test -z "$show_help"; then
 	  case "$dir" in
 	  /*)
 	    # Absolute path.
-	    rpath="$rpath:$dir/$objdir"
+	    rpath="$rpath$dir:"
 	    ;;
 	  *)
 	    # Relative path: add a thisdir entry.
-	    rpath="$rpath:\$thisdir/$dir/$objdir"
+	    rpath="$rpath\$thisdir/$dir:"
 	    ;;
 	  esac
 	done
-
-        # Strip the ugly leading colon.
-        rpath=`echo "$rpath" | sed 's/^://'`
-
-        # Prettify the rpath for the link command.
-        linkrpath=`echo "$rpath" | sed 's%\$thisdir/%%g'`
       fi
 
       # Delete the old output file.
       $run $rm $output
 
-      if test "$hardcode_minus_L" != yes; then
-	# Things are fine, the world is a beautiful place.
-	$show "$compile_command"
-
-      elif test "$hardcode_shlibpath_var" = no; then
-	# We just need to export the shlibpath for the link command.
-	$show "$shlibpath_var=$linkrpath $compile_command"
-	eval "$shlibpath_var=$linkrpath"
-	eval "export $shlibpath_var"
-
-      else
-	# AGH! Flame the AIX and HP-UX people for me, will ya?
-	echo "$progname: warning: using a buggy hardcoding system linker" 1>&2
-	echo "$progname: relinking will be required before \`$output' can be installed" 1>&2
-
-	$show "$compile_command"
+      if test -n "$compile_shlibpath"; then
+	compile_command="$shlibpath_var=$compile_shlibpath\$$shlibpath_var $compile_command"
+      fi
+      if test -n "$finalize_shlibpath"; then
+	finalize_command="$shlibpath_var=$finalize_shlibpath\$$shlibpath_var $finalize_command"
       fi
 
-      $run $compile_command || exit $?
+      case "$hardcode_action" in
+      relink)
+	# AGH! Flame the AIX and HP-UX people for me, will ya?
+	echo "$progname: warning: using a buggy system linker" 1>&2
+	echo "$progname: relinking will be required before \`$output' can be installed" 1>&2
+	;;
+      esac
+
+      $show "$compile_command"
+      eval "$run $compile_command" || exit $?
 
       # Now create the wrapper script.
       echo "creating $output"
@@ -828,22 +883,10 @@ else
   absdir=\`cd "\$thisdir" && pwd\`
   test -n "\$absdir" && thisdir="\$absdir"
 
-  program="\$thisdir/$objdir/$output"
-EOF
+  progdir="\$thisdir/$objdir"
+  program="$output"
 
-	# Export our shlibpath_var if we have one.
-	if test -n "$shlibpath_var" && test -n "$rpath"; then
-	  cat >> $output <<EOF
-
-  # Add our own library path to $shlibpath_var
-  $shlibpath_var="$rpath:\$$shlibpath_var"
-  export $shlibpath_var
-EOF
-	fi
-
-	cat >>$output <<EOF
-
-  if test -f "\$program"; then
+  if test -f "\$progdir/\$program"; then
     # Run the actual program with our arguments.
     args=
     for arg
@@ -851,13 +894,31 @@ EOF
       # Quote arguments (to preserve shell metacharacters).
       args="\$args '\$arg'"
     done
+
+    # Export the path to the program.
+    PATH="\$progdir:\$PATH"
+    export PATH
+EOF
+
+	# Export our shlibpath_var if we have one.
+	if test -n "$shlibpath_var" && test -n "$rpath"; then
+	  cat >> $output <<EOF
+
+    # Add our own library path to $shlibpath_var
+    $shlibpath_var="$rpath\$$shlibpath_var"
+    export $shlibpath_var
+EOF
+	fi
+
+        cat >> $output <<EOF
+
     eval "exec \$program \$args"
 
     echo "\$0: cannot exec \$program \$args"
     exit 1
   else
     # The program doesn't exist.
-    echo "\$0: error: \$program does not exist" 1>&2
+    echo "\$0: error: \$progdir/\$program does not exist" 1>&2
     echo "This script is just a wrapper for \$program." 1>&2
     echo "See the $PACKAGE documentation for more information." 1>&2
     exit 1
@@ -1168,7 +1229,7 @@ EOF
 	    fi
 	  done
 
-	  if test "$hardcode_minus_L" = yes && test "$hardcode_shlibpath_var" != no; then
+	  if test "$hardcode_direct" != no && test "$hardcode_minus_L" != no && test "$hardcode_shlibpath_var" != no; then
 	    if test "$finalize" = no; then
 	      echo "$progname: warning: cannot relink \`$file' on behalf of your buggy system linker" 1>&2
 	    else
