* ltconfig.in (available_tags): The name of each newly added tagged configuration is appended to this list.  This is done at ltconfig time so that the generated `libtool' script need not determine which tags it supports everytime it is used.  The available_tags variable is used by `ltmain.in' to iterate over each of the tagged configurations when attempting to automatically choose which one to use for the supplied compile/link command. * ltmain.in: Added ability to automatically determine which tagged configuration to use based on the compiler found in the supplied base compile command. (available_tags): This new variable contains a list of available tagged configurations.  This gets generated at ltconfig time. (object_name, old_object): Renamed these to pic_object and non_pic_object, respectively. * doc/libtool.texi (Configuration tags): Updated documentation. Libtool now has the ability to infer which tagged configuration to use based on the compiler found in the supplied base compile command. * tagdemo/configure.in, tagdemo/configure: Removed explicit substitution of "--tag=CXX" in $LIBTOOL.  The newly added automatic selection of tagged configurations obviates the need to explicitly specify which tag to use.

diff --git a/ltmain.in b/ltmain.in
--- a/ltmain.in
+++ b/ltmain.in
@@ -423,6 +423,36 @@ if test -z "$show_help"; then
       fi
     done
 
+    # Infer tagged configuration to use if any are available and
+    # if one wasn't chosen via the "--tag" command line option.
+    # Only attempt this if the compiler in the base compile
+    # command doesn't match the default compiler.
+    if test -n "$available_tags" && test -z "$tagname" && echo $base_compile | grep -v $CC > /dev/null; then
+      for z in $available_tags; do
+        if grep "^### BEGIN LIBTOOL TAG CONFIG: $z$" < "$0" > /dev/null; then
+	  # Evaluate the configuration.
+	  eval "`sed -n -e '/^### BEGIN LIBTOOL TAG CONFIG: '$z'$/,/^### END LIBTOOL TAG CONFIG: '$z'$/p' < $0`"
+          if echo $base_compile | grep $CC > /dev/null; then
+            # The compiler in the base compile command matches
+            # the one in the tagged configuration.
+            # Assume this is the tagged configuration we want.
+            tagname=$z
+            break
+          fi
+        fi
+      done
+      # If $tagname still isn't set, then no tagged configuration
+      # was found and let the user know that the "--tag" command
+      # line option must be used.
+      if test -z "$tagname"; then
+        echo "$modename: unable to infer tagged configuration"
+        echo "$modename: specify a tag with \`--tag'" 1>&2
+	exit 1
+#     else
+#       echo "$modename: using $tagname tagged configuration"
+      fi
+    fi
+
     case "$user_target" in
     set)
       ;;
@@ -522,7 +552,7 @@ compiler."
 
     $run $rm "$libobj"
 
-    # Create a libtool object file (analogous to a `.la' file),
+    # Create a libtool object file (analogous to a ".la" file),
     # but don't create it if we're doing a dry run.
     test -z "$run" && cat > $libobj <<EOF
 # $libobj - a libtool object file
@@ -564,7 +594,7 @@ EOF
 
       # Append the name of the PIC object to the libtool object file.
       test -z "$run" && cat >> $libobj <<EOF
-object_name='$output_obj'
+pic_object='$output_obj'
 
 EOF
 
@@ -613,7 +643,7 @@ compiler."
       # No PIC object so indicate it doesn't exist in the libtool
       # object file.
       test -z "$run" && cat >> $libobj <<EOF
-object_name=none
+pic_object=none
 
 EOF
     fi
@@ -636,7 +666,7 @@ EOF
       # Only append if the libtool object file exists.
       test -z "$run" && cat >> $libobj <<EOF
 # Name of the non-PIC object.
-old_object='$obj'
+non_pic_object='$obj'
 
 EOF
 
@@ -685,7 +715,7 @@ compiler."
       # Only append if the libtool object file exists.
       test -z "$run" && cat >> $libobj <<EOF
 # Name of the non-PIC object.
-old_object=none
+non_pic_object=none
 
 EOF
     fi
@@ -752,7 +782,7 @@ EOF
     module=no
     no_install=no
     objs=
-    old_objects=
+    non_pic_objects=
     prefer_static_libs=no
     preload=no
     prev=
@@ -1174,8 +1204,8 @@ EOF
 
 	# Check to see that this really is a libtool object.
 	if (sed -e '2q' $arg | egrep "^# Generated by .*$PACKAGE") >/dev/null 2>&1; then
-          object_name=
-          old_object=
+          pic_object=
+          non_pic_object=
 
           # Read the .lo file
           # If there is no directory component, then add one.
@@ -1184,10 +1214,10 @@ EOF
           *) . ./$arg ;;
           esac
 
-          if test -z "$object_name" || \
-             test -z "$old_object" ||
-             test "$object_name" = none && \
-             test "$old_object" = none; then
+          if test -z "$pic_object" || \
+             test -z "$non_pic_object" ||
+             test "$pic_object" = none && \
+             test "$non_pic_object" = none; then
             $echo "$modename: cannot find name of object for \`$arg'" 1>&2
             exit 1
           fi
@@ -1200,12 +1230,12 @@ EOF
 	    xdir="$xdir/"
 	  fi
 
-          if test "$object_name" != none; then
+          if test "$pic_object" != none; then
             # Prepend the subdirectory the object is found in.
-	    object_name="$xdir$object_name"
+	    pic_object="$xdir$pic_object"
 
 	    if test "$prev" = dlfiles; then
-	      dlfiles="$dlfiles $object_name"
+	      dlfiles="$dlfiles $pic_object"
 	      if test "$build_libtool_libs" = yes && test "$dlopen" = yes; then
 	        prev=
 	        continue
@@ -1218,21 +1248,21 @@ EOF
 	    # CHECK ME:  I think I busted this.  -Ossama
             if test "$prev" = dlprefiles; then
 	      # Preload the old-style object.
-	      dlprefiles="$dlprefiles $object_name"
+	      dlprefiles="$dlprefiles $pic_object"
 	      prev=
             fi
 
             # A PIC object.
-	    libobjs="$libobjs $object_name"
+	    libobjs="$libobjs $pic_object"
           fi
 
           # Non-PIC object.
-          if test "$old_object" != none; then
+          if test "$non_pic_object" != none; then
             # Prepend the subdirectory the object is found in.
-	    old_object="$xdir$old_object"
+	    non_pic_object="$xdir$non_pic_object"
 
             # A standard non-PIC object
-            old_objects="$old_objects $old_object"
+            non_pic_objects="$non_pic_objects $non_pic_object"
           fi
         else
           # Only an error if not doing a dry-run.
@@ -1250,10 +1280,10 @@ EOF
 	      xdir="$xdir/"
 	    fi
 
-            object_name=`$echo "X${xdir}${objdir}/${arg}" | $Xsed -e "$lo2o"`
-            old_object=`$echo "X${xdir}${arg}" | $Xsed -e "$lo2o"`
-	    libobjs="$libobjs $object_name"
-            old_objects="$old_objects $old_object"
+            pic_object=`$echo "X${xdir}${objdir}/${arg}" | $Xsed -e "$lo2o"`
+            non_pic_object=`$echo "X${xdir}${arg}" | $Xsed -e "$lo2o"`
+	    libobjs="$libobjs $pic_object"
+            non_pic_objects="$non_pic_objects $non_pic_object"
           fi
 	fi
 	;;
@@ -1367,6 +1397,38 @@ EOF
       $echo "$modename: the \`$prevarg' option requires an argument" 1>&2
       $echo "$help" 1>&2
       exit 1
+    fi
+
+    # Infer tagged configuration to use if any are available and
+    # if one wasn't chosen via the "--tag" command line option.
+    # Only attempt this if the compiler in the base link
+    # command doesn't match the default compiler.
+    if test -n "$available_tags" \
+       && test -z "$tagname" \
+       && echo $compile_command | grep -v $CC > /dev/null; then
+      for z in $available_tags; do
+        if grep "^### BEGIN LIBTOOL TAG CONFIG: $z$" < "$0" > /dev/null; then
+	  # Evaluate the configuration.
+	  eval "`sed -n -e '/^### BEGIN LIBTOOL TAG CONFIG: '$z'$/,/^### END LIBTOOL TAG CONFIG: '$z'$/p' < $0`"
+          if echo $compile_command | grep $CC > /dev/null; then
+            # The compiler in $compile_command matches
+            # the one in the tagged configuration.
+            # Assume this is the tagged configuration we want.
+            tagname=$z
+            break
+          fi
+        fi
+      done
+      # If $tagname still isn't set, then no tagged configuration
+      # was found and let the user know that the "--tag" command
+      # line option must be used.
+      if test -z "$tagname"; then
+        echo "$modename: unable to infer tagged configuration"
+        echo "$modename: specify a tag with \`--tag'" 1>&2
+	exit 1
+#     else
+#       echo "$modename: using $tagname tagged configuration"
+      fi
     fi
 
     if test "$export_dynamic" = yes && test -n "$export_dynamic_flag_spec"; then
@@ -2364,7 +2426,7 @@ EOF
 	oldlibs="$oldlibs $output_objdir/$libname.$libext"
 
 	# Transform .lo files to .o files.
-	oldobjs="$objs "`$echo "X$libobjs" | $SP2NL | $Xsed -e '/\.'${libext}'$/d' -e "$lo2o" | $NL2SP`
+      oldobjs="$objs "`$echo "X$libobjs" | $SP2NL | $Xsed -e '/\.'${libext}'$/d' -e "$lo2o" | $NL2SP`
       fi
 
       # Eliminate all temporary directories.
@@ -3614,7 +3676,7 @@ fi\
 	  oldobjs="$libobjs_save"
 	  build_libtool_libs=no
 	else
-	  oldobjs="$objs$old_deplibs $old_objects"
+	  oldobjs="$objs$old_deplibs $non_pic_objects"
 	fi
 	addlibs="$old_convenience"
       fi
