* libltdl/configure.in: check for shl_load in libdld * libltdl/ltdl.c (shl_close, shl_sym): use (shl_t *) instead of shl_t * ltconfig.in (check for gcc): removed a bogus line,   check for shl_load in libdld * ltmain.in: added a warning to the header of the .la file   to warn users against deleting the file,   link shared against static libraries if   deplibs_check_method == pass_all

diff --git a/ltmain.in b/ltmain.in
--- a/ltmain.in
+++ b/ltmain.in
@@ -1783,16 +1783,27 @@ compiler."
 	    esac
 	  fi
 	  test "$add_name" = yes && deplibs="$deplibs -l$name"
-	elif test "$build_libtool_libs" = yes && test "$deplibs_check_method" != pass_all; then
-	  # We're trying link a shared library against a static one
-	  # but the system doesn't support it.
-	  # Just print a warning and add the library to dependency_libs so
-	  # that the program can be linked against the static library.
-	  echo
-	  echo "*** Warning: This library needs some functionality provided by $libname."
-	  echo "*** I have the capability to make that library automatically link in when"
-	  echo "*** you link to this library.  But I can only do this if you have a"
-	  echo "*** shared version of the library, which you do not appear to have."
+	elif test "$build_libtool_libs" = yes; then
+	  if test "$deplibs_check_method" != pass_all; then
+	    # We're trying link a shared library against a static one
+	    # but the system doesn't support it.
+	    # Just print a warning and add the library to dependency_libs so
+	    # that the program can be linked against the static library.
+	    echo
+	    echo "*** Warning: This library needs some functionality provided by $libname."
+	    echo "*** I have the capability to make that library automatically link in when"
+	    echo "*** you link to this library.  But I can only do this if you have a"
+	    echo "*** shared version of the library, which you do not appear to have."
+	  else
+	    # Check for old archives if we don't build new libraries.
+	    if test -n "$pic_flag" && test -z "$old_library"; then
+	      $echo "$modename: cannot find static library for \`$lib'" 1>&2
+	      exit 1
+	    fi
+	    convenience="$convenience $dir/$old_library"
+	    old_convenience="$old_convenience $dir/$old_library"
+	    deplibs="$deplibs $dir/$old_library"
+	  fi
 	fi
 
 	if test -n "$dependency_libs"; then
@@ -2560,15 +2571,6 @@ EOF
 	fi
 	name=`$echo "X$laname" | $Xsed -e 's/\.la$//' -e 's/^lib//'`
 	
-	if test -z "$libdir"; then
-	  # It is a libtool convenience library, so add in its objects.
-	  convenience="$convenience $dir/$old_library"
-	  old_convenience="$old_convenience $dir/$old_library"
-	  compile_command="$compile_command $dir/$old_library"
-	  finalize_command="$finalize_command $dir/$old_library"
-	  continue
-	fi
-
 	if test "$build_libtool_libs" = yes && test -n "$library_names"; then
 	  # We need to hardcode the library path
 	  if test -n "$shlibpath_var"; then
@@ -2604,13 +2606,24 @@ EOF
 	  esac
 	fi
 
-	if test "$alldeplibs" = yes && \
-	   test "$build_libtool_libs" = yes && \
-	   test -n "$library_names"; then
-	  # Do we only need to link against static libraries?
-	  continue
+	if test "$alldeplibs" = yes; then
+	  if test "$deplibs_check_method" = pass_all ||
+	     (test "$build_libtool_libs" = yes && \
+	      test -n "$library_names"); then
+	    # Do we only need to link against static libraries?
+	    continue
+	  fi
 	fi
 	
+	if test -z "$libdir"; then
+	  # It is a libtool convenience library, so add in its objects.
+	  convenience="$convenience $dir/$old_library"
+	  old_convenience="$old_convenience $dir/$old_library"
+	  compile_command="$compile_command $dir/$old_library"
+	  finalize_command="$finalize_command $dir/$old_library"
+	  continue
+	fi
+
 	if test "$build_libtool_libs" = yes && test -n "$library_names"; then
 	  link_against_libtool_libs="$link_against_libtool_libs $lib"
 
@@ -3483,8 +3496,11 @@ fi\
 	  fi
 	  $rm $output
 	  $echo > $output "\
-# $output - a libtool library file
+# $outputname.la - a libtool library file
 # Generated by $PROGRAM - GNU $PACKAGE $VERSION$TIMESTAMP
+#
+# Please DO NOT delete this file!
+# It is necessary for linking the library.
 
 # The name that we can dlopen(3).
 dlname='$dlname'
