*** empty log message ***

diff --git a/ltmain.sh.in b/ltmain.sh.in
--- a/ltmain.sh.in
+++ b/ltmain.sh.in
@@ -174,7 +174,7 @@ if test -z "$show_help"; then
     done
 
     # Get the name of the library object.
-    libobj=`echo "$srcfile" | sed -e 's%^.*/%%' -e 's/\.c$/.lo/'`
+    libobj=`echo "$srcfile" | sed -e 's%^.*/%%; s/\.[Sc]$/.lo/'`
     case $libobj in
     *.lo) obj=`echo "$libobj" | sed -e 's/\.lo$/.o/'` ;;
     *)
@@ -254,12 +254,12 @@ if test -z "$show_help"; then
     vinfo=
 
 
-    # Maybe set the library names to libNAME_p.a if we are doing profiling.
-    if echo " $@ " | egrep "[ 	]$profile_flag_pattern[	 ]" > /dev/null 2>&1; then
-      suffix=p
-    else
-      suffix=
-    fi
+#    FIXME Maybe set the library names to libNAME_p.a if we are doing profiling.
+#    if echo " $@ " | egrep "[ 	]$profile_flag_pattern[	 ]" > /dev/null 2>&1; then
+#      suffix=p
+#    else
+#      suffix=
+#    fi
 
     for arg
     do
@@ -321,7 +321,7 @@ if test -z "$show_help"; then
 
       # Automake's ansi2knr support code uses the "._o" and ".l_o" object
       # suffixes.
-      *.o | *._o)
+      *.o | *._o | *.a)
 	# A standard object.
 	objs="$objs $arg"
 	;;
@@ -337,73 +337,64 @@ if test -z "$show_help"; then
 	test "$dir" = "$arg" && dir=.
 	file=`echo "$arg" | sed 's%^.*/%%'`
 
-	case "$file" in
-	lib?*.la)
-	  link_against_libtool_libs="$link_against_libtool_libs $arg"
-	  if test "$build_libtool_libs" = yes; then
-	    # Specify the library as -lNAME.
-	    carg="-l`echo "$file" | sed 's/lib\(..*\)\.la$/\1/'`"
-	    farg="$carg"
+	link_against_libtool_libs="$link_against_libtool_libs $arg"
+	if test "$build_libtool_libs" = yes; then
+	  # Specify the library as -lNAME.
+	  carg="-l`echo "$file" | sed 's/lib\(..*\)\.la$/\1/'`"
+	  farg="$carg"
 
-	    if test -n "$shlibpath_var"; then
-	      # Make sure the rpath contains only unique directories.
-	      case "$temp_rpath " in
-	      "* $dir *") ;;
-	      *) temp_rpath="$temp_rpath $dir" ;;
-	      esac
-	    fi
+	  if test -n "$shlibpath_var"; then
+	    # Make sure the rpath contains only unique directories.
+	    case "$temp_rpath " in
+	    "* $dir *") ;;
+	    *) temp_rpath="$temp_rpath $dir" ;;
+	    esac
+	  fi
 
-	    # Check to see that this really is a libtool archive.
-	    if egrep "^# Generated by $PROGRAM" $arg >/dev/null 2>&1; then :
-	    else
-	      echo "$progname: \`$arg' is not a valid libtool archive" 1>&2
-	      exit 1
-	    fi
-
-	    libdir=
-	    . $dir/$file
-
-	    if test -z "$libdir"; then
-	      echo "$progname: \`$arg' contains no -rpath information" 1>&2
-	      exit 1
-	    fi
-
-	    if test -n "$link_rpath_flag"; then
-	      carg="`eval echo \"$link_rpath_flag\"` $carg"
-	      farg="$carg"
-	    fi
-
-	    if test "$hardcode_minus_L" != yes; then
-	      # Just give the right -L directory flag.
-	      carg="-L$dir/$objdir $carg"
-
-	    elif test "$hardcode_shlibpath_var" = yes; then
-	      # Give an absolute path to the library.
-	      case "$dir" in
-	      /*) absdir="$dir" ;;
-	      *)
-		absdir=`cd $dir && pwd`
-		if test -z "$absdir"; then
-		  echo "$progname: cannot determine absolute pathname of \`$dir'" 1>&2
-		  exit 1
-		fi
-		;;
-	      esac
-	      carg="-L$absdir/$objdir $carg"
-	      farg="-L$libdir $farg"
-	    fi
+	  # Check to see that this really is a libtool archive.
+	  if egrep "^# Generated by $PROGRAM" $arg >/dev/null 2>&1; then :
 	  else
-	    # Transform directly to old archives if we don't build new libraries.
-	    carg="$dir/$objdir/`echo "$file" | sed 's/\.la$/.a/'`"
+	    echo "$progname: \`$arg' is not a valid libtool archive" 1>&2
+	    exit 1
+	  fi
+
+	  libdir=
+	  . $dir/$file
+
+	  if test -z "$libdir"; then
+	    echo "$progname: \`$arg' contains no -rpath information" 1>&2
+	    exit 1
+	  fi
+
+	  if test -n "$link_rpath_flag"; then
+	    carg="`eval echo \"$link_rpath_flag\"` $carg"
 	    farg="$carg"
 	  fi
-	  ;;
-	*)
-	  echo "$progname: improperly formed library name \`$arg' (not libNAME.la)" 1>&2
-	  echo "$help"
-	  exit 1
-	  ;;
-	esac
+
+	  if test "$hardcode_minus_L" != yes; then
+	    # Just give the right -L directory flag.
+	    carg="-L$dir/$objdir $carg"
+
+	  elif test "$hardcode_shlibpath_var" = yes; then
+	    # Give an absolute path to the library.
+	    case "$dir" in
+	    /*) absdir="$dir" ;;
+	    *)
+	      absdir=`cd $dir && pwd`
+	      if test -z "$absdir"; then
+	        echo "$progname: cannot determine absolute pathname of \`$dir'" 1>&2
+		exit 1
+	      fi
+      	      ;;
+            esac
+            carg="-L$absdir/$objdir $carg"
+            farg="-L$libdir $farg"
+          fi
+        else
+          # Transform directly to old archives if we don't build new libraries.
+          carg="$dir/$objdir/`echo "$file" | sed 's/\.la$/.a/'`"
+          farg="$carg"
+        fi
 	;;
 
       *)
@@ -453,7 +444,7 @@ if test -z "$show_help"; then
       fi
       ;;
 
-    lib?*.la)
+    *.la)
       libname=`echo "$output" | sed 's/\.la$//'`
 
       if test -n "$objs"; then
@@ -603,6 +594,9 @@ if test -z "$show_help"; then
 	  linknames="$linknames $objdir/$link"
 	done
 
+	# Use standard objects if they are PIC.
+	test -z "$pic_flag" && libobjs=`echo "$libobjs " | sed 's/\.lo /.o /g; s/\.l_o /._o /g; s/ $//g'`
+
 	# Do each of the archive commands.
 	cmds=`eval echo \"$archive_cmds\"`
 	IFS="${IFS= 	}"; save_ifs="$IFS"; IFS=';'
@@ -619,12 +613,6 @@ if test -z "$show_help"; then
 	  $run $ln_s $realname $link || exit $?
 	done
       fi
-      ;;
-
-    *.la)
-      echo "$progname: improperly formed library name \`$arg' (not libNAME.la)" 1>&2
-      echo "$help"
-      exit 1
       ;;
 
     *.lo | *.o)
@@ -710,8 +698,9 @@ if test -z "$show_help"; then
       fi
 
       if test -n "$libobjs"; then
-	# FIXME - transform all the library objects into standard objects.
-	echo "$progname: warning: library object files should not be used to build programs" 1>&2
+	# Transform all the library objects into standard objects.
+	compile_command=`echo "$compile_command " | sed 's/\.lo /.o /g; s/\.l_o /._o /g; s/ $//g'`
+	
       fi
 
       if test -z "$link_against_libtool_libs" || test "$build_libtool_libs" != yes; then
@@ -1178,14 +1167,14 @@ EOF
       esac
     done
       
-    # Install any profiled libraries, too.
-    newfiles=
-    for file in $staticlibs; do
-      newfiles="$newfiles $file"
-      pfile=`echo "$file" | sed 's/\.a$/_p.a/'`
-      test -f "$pfile" && newfiles="$newfiles $pfile"
-    done
-    staticlibs="$newfiles"
+# FIXME Install any profiled libraries, too.
+#    newfiles=
+#    for file in $staticlibs; do
+#      newfiles="$newfiles $file"
+#      pfile=`echo "$file" | sed 's/\.a$/_p.a/'`
+#      test -f "$pfile" && newfiles="$newfiles $pfile"
+#    done
+#    staticlibs="$newfiles"
 
     for file in $staticlibs; do
       name=`echo "$file" | sed 's%^.*/%%'`
@@ -1287,7 +1276,7 @@ EOF
       name=`echo "$file" | sed -e 's%^.*/%%'`
 
       case "$name" in
-      lib*.la)
+      *.la)
 	# Possibly a libtool archive, so verify it.
 	if egrep "^# Generated by $PROGRAM" $file >/dev/null 2>&1; then
 	  . $dir/$name
@@ -1315,7 +1304,7 @@ EOF
 
   NONE)
     echo "$progname: you must specify a MODE" 1>&2
-    echo "$help" 1>&2
+    echo "$generic_help" 1>&2
     exit 1
     ;;
   esac
