*** empty log message ***

diff --git a/ltmain.sh.in b/ltmain.sh.in
--- a/ltmain.sh.in
+++ b/ltmain.sh.in
@@ -310,22 +310,22 @@ if test -z "$show_help"; then
 	      esac
 	    fi
 
+	    # Check to see that this really is a libtool archive.
+	    if egrep "^# Generated by $PROGRAM" $arg >/dev/null 2>&1; then :
+	    else
+	      echo "$progname: \`$arg' is not a valid libtool archive" 1>&2
+	      exit 1
+	    fi
+
+	    libdir=
+	    . $file
+
+	    if test -z "$libdir"; then
+	      echo "$progname: \`$arg' contains no -rpath information" 1>&2
+	      exit 1
+	    fi
+
 	    if test -n "$link_rpath_flag"; then
-	      # Check to see that this really is a libtool archive.
-	      if egrep "^# Generated by $PROGRAM" $arg >/dev/null 2>&1; then :
-	      else
-		echo "$progname: \`$arg' is not a valid libtool archive" 1>&2
-		exit 1
-	      fi
-
-	      libdir=
-	      . $file
-
-	      if test -z "$libdir"; then
-		echo "$progname: \`$arg' contains no -rpath information" 1>&2
-		exit 1
-	      fi
-
 	      carg="`eval echo \"$link_rpath_flag\"` $carg"
 	      farg="$carg"
 	    fi
@@ -336,14 +336,18 @@ if test -z "$show_help"; then
 
 	    elif test "$hardcode_shlibpath_var" = yes; then
 	      # Give an absolute path to the library.
-	      dir=`cd $dir && pwd`
 	      case "$dir" in
-	      /*) carg="-L`cd $dir && pwd`/$objdir $arg" ;;
+	      /*) absdir="$dir" ;;
 	      *)
-		echo "$progname: cannot determine absolute pathname of \`$dir'" 1>&2
-		exit 1
+		absdir=`cd $dir && pwd`
+		if test -z "$absdir"; then
+		  echo "$progname: cannot determine absolute pathname of \`$dir'" 1>&2
+		  exit 1
+		fi
 		;;
 	      esac
+	      carg="-L$absdir/$objdir $carg"
+	      farg="-L$libdir $farg"
 	    fi
 	  else
 	    # Transform directly to old archives if we don't build new libraries.
@@ -453,10 +457,15 @@ if test -z "$show_help"; then
       case "$version_type" in
       none) ;;
 
-      hpux)
+      libtool)
+	version_vars="$version_vars versuffix"
+	versuffix="$current.$age.$revision"
+	;;
+
+      linux)
 	version_vars="$version_vars major versuffix"
-	major="$current"
-	versuffix="$current.$revision"
+	major=`expr $current - $age`
+	versuffix="$major.$age.$revision"
 	;;
 
       osf)
@@ -476,14 +485,9 @@ if test -z "$show_help"; then
 	verstring="$verstring:${current}.0"
 	;;
 
-      solaris)
-	version_vars="$version_vars major versuffix"
-	major=`expr $current - $age`
-	verstring="$major.$age.$revision"
-	;;
-
       sunos)
-	version_vars="$version_vars versuffix"
+	version_vars="$version_vars major versuffix"
+	major="$current"
 	versuffix="$current.$revision"
 	;;
 
@@ -497,6 +501,15 @@ if test -z "$show_help"; then
       # Maybe add a suffix.
       test -n "$suffix" && libname=$libname"_$suffix"
 
+      # Create the output directory, or remove our outputs if we need to.
+      if test -d $objdir; then
+        $show "$rm $objdir/$libname.*"
+        $run $rm $objdir/$libname.*
+      else
+        $show "$mkdir $objdir"
+	$run $mkdir $objdir || exit $?
+      fi
+
       if test "$build_libtool_libs" = yes; then
 	# Get the real and link names of the library.
 	library_names=`eval echo \"$lib_names\"`
@@ -504,7 +517,7 @@ if test -z "$show_help"; then
 	realname="$2"
 	shift; shift
 
-	if test -n "$soname"; then
+	if test -n "$soname_spec"; then
 	  soname=`eval echo \"$soname_spec\"`
 	else
 	  soname="$realname"
@@ -517,22 +530,13 @@ if test -z "$show_help"; then
 	  linknames="$linknames $objdir/$link"
 	done
 
-	# Create the output directory, or remove our outputs if we need to.
-	if test -d $objdir; then
-	  $show "$rm $objdir/$libname.*"
-	  $run $rm $objdir/$libname.*
-	else
-	  $show "$mkdir $objdir"
-	  $run $mkdir $objdir || exit $?
-	fi
-
 	# Do each of the archive commands.
 	cmds=`eval echo \"$archive_cmds\"`
-	IFS=${IFS= 	}; save_ifs="$IFS"; IFS=';'
+	IFS="${IFS= 	}"; save_ifs="$IFS"; IFS=';'
 	for cmd in $cmds; do
 	  IFS="$save_ifs"
 	  $show "$cmd"
-	  $run $cmd || exit $?
+	  eval "$run $cmd" || exit $?
 	done
 	IFS="$save_ifs"
 
@@ -553,8 +557,9 @@ if test -z "$show_help"; then
     *)
       if test -z "$link_against_libtool_libs" || test "$build_libtool_libs" != yes; then
 	# We have no uninstalled library dependencies, so finalize right now.
-	$show "$finalize_command"
-	$run $finalize_command
+	compile_command=`echo "$compile_command" | sed "s%-o $objdir/%-o %"`
+	$show "$compile_command"
+	$run $compile_command
 	exit $?
       fi
 
@@ -639,6 +644,11 @@ else
   # Find the directory that this script lives in.
   thisdir=\`echo \$0 | sed 's%/[^/]*$%%'\`
   test "x\$thisdir" = "x\$0" && thisdir=.
+
+  # Try to get the absolute directory name.
+  absdir=\`cd "\$thisdir" && pwd\`
+  test -n "\$absdir" && thisdir="\$absdir"
+
   program="\$thisdir/$objdir/$output"
 EOF
 
@@ -700,11 +710,11 @@ EOF
       cmds=`eval echo \"$old_archive_cmds\"`
 
       # Do each command in the archive commands.
-      IFS=${IFS= 	}; save_ifs="$IFS"; IFS=';'
+      IFS="${IFS= 	}"; save_ifs="$IFS"; IFS=';'
       for cmd in $cmds; do
         IFS="$save_ifs"
         $show "$cmd"
-	$run $cmd || exit $?
+	eval "$run $cmd" || exit $?
       done
       IFS="$save_ifs"
     fi
@@ -771,7 +781,10 @@ EOF
       -g) prev="-g" ;;
       -m) prev="-m" ;;
       -o) prev="-o" ;;
-      -s) stripme=" -s" ;;
+      -s)
+	stripme=" -s"
+	continue
+	;;
       -*) ;;
 
       *)
@@ -877,22 +890,33 @@ EOF
 	  shift
 	  shift
 
-	  # FIXME support stripping libraries
-	  if test -n "$stripme"; then
-	    echo "$progname: will not strip libraries (yet)" 1>&2
-	  fi
-
 	  # Install the shared library and build the symlinks.
 	  $show "$install_prog $dir/$realname $destdir/$realname"
-	  $run $install_prog $dir/$realname $destdir/$realname || exit $?
+	  eval "$run $install_prog $dir/$realname $destdir/$realname" || exit $?
+
+	  # Support stripping libraries.
+	  if test -n "$stripme"; then
+	    if test -n "$striplib"; then
+	      $show "$striplib $destdir/$realname"
+	      $run $striplib $destdir/$realname || exit $?
+	    else
+	      echo "$progname: warning: no library stripping program" 1>&2
+	    fi
+	  fi
 
 	  if test -n "$1"; then
 	    # Delete the old symlinks.
-	    $show "$rm $@"
-	    $run $rm $@
+            rmcmd="$rm"
+            for linkname
+            do
+              rmcmd="$rmcmd $destdir/$linkname"
+            done
+            $show "$rmcmd"
+            $run $rmcmd
 
 	    # ... and create new ones.
-	    for linkname; do
+	    for linkname
+	    do
 	      $show "$ln_s $realname $destdir/$linkname"
 	      $run $ln_s $realname $destdir/$linkname
 	    done
@@ -901,11 +925,11 @@ EOF
 	  # Do each command in the postinstall commands.
 	  lib="$destdir/$realname"
 	  cmds=`eval echo \"$postinstall_cmds\"`
-	  IFS=${IFS= 	}; save_ifs="$IFS"; IFS=';'
+	  IFS="${IFS= 	}"; save_ifs="$IFS"; IFS=';'
 	  for cmd in $cmds; do
 	    IFS="$save_ifs"
 	    $show "$cmd"
-	    $run $cmd || exit $?
+	    eval "$run $cmd" || exit $?
 	  done
 	  IFS="$save_ifs"
 	fi
@@ -940,6 +964,7 @@ EOF
 	    exit 1
 	  fi
 
+	  finalize=yes
 	  for lib in $link_against_libtool_libs; do
 	    # Check to see that each library is installed.
 	    libdir=
@@ -952,18 +977,23 @@ EOF
 	    elif test -f "$libfile"; then :	      
 	    else
 	      echo "$progname: warning: \`$lib' has not been installed in \`$libdir'" 1>&2
+	      finalize=no
 	    fi
 	  done
 
 	  if test "$hardcode_minus_L" = yes && test "$hardcode_shlibpath_var" = yes; then
-	    echo "$progname: warning: relinking \`$file' on behalf of your buggy system linker"
-	    $show "$finalize_command"
-	    if $run $finalize_command; then :
+	    if test "$finalize" = no; then
+	      echo "$progname: warning: cannot relink \`$file' on behalf of your buggy system linker"
 	    else
-	      echo "$progname: error: relink \`$file' with the above command before installing it" 1>&2
-	      continue
+	      echo "$progname: warning: relinking \`$file' on behalf of your buggy system linker"
+	      $show "$finalize_command"
+	      if $run $finalize_command; then :
+	      else
+		echo "$progname: error: relink \`$file' with the above command before installing it" 1>&2
+		continue
+	      fi
+	      file="$objdir/$file"T
 	    fi
-	    file="$objdir/$file"T
 	  else
 	    # Install the binary that we compiled earlier.
 	    dir=`echo "$file" | sed 's%/[^/]*$%%'`
@@ -996,21 +1026,26 @@ EOF
       # Set up the ranlib parameters.
       oldlib="$destdir/$name"
 
-      # FIXME support stripping libraries
-      if test -n "$stripme"; then
-	echo "$progname: will not strip libraries (yet)" 1>&2
-      fi
-
       $show "$install_prog $file $oldlib"
       $run $install_prog $file $oldlib || exit $?
 
+      # Support stripping libraries.
+      if test -n "$stripme"; then
+	if test -n "$striplib"; then
+	  $show "$striplib $oldlib"
+	  $run $striplib $oldlib || exit $?
+	else
+	  echo "$progname: warning: no library stripping program" 1>&2
+	fi
+      fi
+
       # Do each command in the postinstall commands.
       cmds=`eval echo \"$old_postinstall_cmds\"`
-      IFS=${IFS= 	}; save_ifs="$IFS"; IFS=';'
+      IFS="${IFS= 	}"; save_ifs="$IFS"; IFS=';'
       for cmd in $cmds; do
         IFS="$save_ifs"
         $show "$cmd"
-        $run $cmd || exit $?
+        eval "$run $cmd" || exit $?
       done
       IFS="$save_ifs"
     done
@@ -1034,18 +1069,19 @@ EOF
     libdirs="$nonopt"
 
     if test -n "$finish_cmds" && test -n "$libdirs"; then
-      for dir; do
+      for dir
+      do
 	libdirs="$libdirs $dir"
       done
 
       for libdir in $libdirs; do
 	# Do each command in the postinstall commands.
 	cmds=`eval echo \"$finish_cmds\"`
-	IFS=${IFS= 	}; save_ifs="$IFS"; IFS=';'
+	IFS="${IFS= 	}"; save_ifs="$IFS"; IFS=';'
 	for cmd in $cmds; do
 	  IFS="$save_ifs"
 	  $show "$cmd"
-	  $run $cmd
+	  eval "$run $cmd"
 	done
 	IFS="$save_ifs"
       done
