*** empty log message ***

diff --git a/ltmain.in b/ltmain.in
--- a/ltmain.in
+++ b/ltmain.in
@@ -22,8 +22,7 @@
 # configuration script generated by Autoconf, you may include it under
 # the same distribution terms that you use for the rest of that program.
 
-#FIXME: echo=echo
-echo='printf %s\n'
+echo=echo
 if test "X`$echo '\t'`" = 'X\t'; then :
 else
   # The Solaris and AIX default echo program unquotes backslashes.
@@ -76,14 +75,14 @@ if test "${LC_ALL+set}" = set; then LC_ALL=C; export LC_ALL; fi
 if test "${LANG+set}"   = set; then LANG=C;   export LANG;   fi
 
 if test "$LTCONFIG_VERSION" != "$VERSION"; then
-  $echo "$progname: ltconfig version \`$LTCONFIG_VERSION' does not match $PROGRAM version \`$VERSION'" 1>&2
-  $echo "Fatal configuration error.  See the $PACKAGE docs for more information." 1>&2
+  echo "$progname: ltconfig version \`$LTCONFIG_VERSION' does not match $PROGRAM version \`$VERSION'" 1>&2
+  echo "Fatal configuration error.  See the $PACKAGE docs for more information." 1>&2
   exit 1
 fi
 
 if test "$build_libtool_libs" != yes && test "$build_old_libs" != yes; then
-  $echo "$progname: not configured to build any kind of library" 1>&2
-  $echo "Fatal configuration error.  See the $PACKAGE docs for more information." 1>&2
+  echo "$progname: not configured to build any kind of library" 1>&2
+  echo "Fatal configuration error.  See the $PACKAGE docs for more information." 1>&2
   exit 1
 fi
 
@@ -131,7 +130,7 @@ do
     ;;
 
   --version)
-    $echo "$PROGRAM (GNU $PACKAGE) $VERSION"
+    echo "$PROGRAM (GNU $PACKAGE) $VERSION"
     exit 0
     ;;
 
@@ -140,16 +139,16 @@ do
     ;;
 
   --features)
-    $echo "host: $host"
+    echo "host: $host"
     if test "$build_libtool_libs" = yes; then
-      $echo "enable shared libraries"
+      echo "enable shared libraries"
     else
-      $echo "disable shared libraries"
+      echo "disable shared libraries"
     fi
     if test "$build_old_libs" = yes; then
-      $echo "enable static libraries"
+      echo "enable static libraries"
     else
-      $echo "disable static libraries"
+      echo "disable static libraries"
     fi
     exit 0
     ;;
@@ -369,8 +368,8 @@ if test -z "$show_help"; then
     # Create an invalid libtool object if no PIC, so that we don't accidentally
     # link it into a program.
     if test "$build_libtool_libs" != yes; then
-      $show "$echo timestamp > $libobj"
-      $run eval "\$echo timestamp > \$libobj" || exit $?
+      $show "echo timestamp > $libobj"
+      $run eval "echo timestamp > \$libobj" || exit $?
     fi
 
     exit 0
@@ -380,7 +379,7 @@ if test -z "$show_help"; then
   link)
     progname="$progname: link"
     CC="$nonopt"
-    allow_undefined=no
+    allow_undefined=yes
     compile_command="$CC"
     finalize_command="$CC"
 
@@ -468,7 +467,8 @@ if test -z "$show_help"; then
 	;;
 
       -allow-undefined)
-	allow_undefined=yes
+	# FIXME: remove this flag sometime in the future.
+	$echo "$progname: \`-allow-undefined' is deprecated because it is the default" 1>&2
 	continue
 	;;
 
@@ -512,6 +512,11 @@ if test -z "$show_help"; then
         ;;
 
       -l*) deplibs="$deplibs $arg" ;;
+
+      -no-undefined)
+	allow_undefined=no
+	continue
+	;;
 
       -o) prev=output ;;
 
@@ -778,8 +783,10 @@ if test -z "$show_help"; then
       esac
 
       # Now actually substitute the argument into the commands.
-      compile_command="$compile_command $arg"
-      finalize_command="$finalize_command $arg"
+      if test -n "$arg"; then
+	compile_command="$compile_command $arg"
+	finalize_command="$finalize_command $arg"
+      fi
     done
 
     if test -n "$prev"; then
@@ -943,7 +950,7 @@ if test -z "$show_help"; then
 
       *)
         $echo "$progname: unknown library version type \`$version_type'" 1>&2
-        $echo "Fatal configuration error.  See the $PACKAGE docs for more information." 1>&2
+        echo "Fatal configuration error.  See the $PACKAGE docs for more information." 1>&2
         exit 1
         ;;
       esac
@@ -1082,8 +1089,8 @@ if test -z "$show_help"; then
       if test "$build_libtool_libs" != yes; then
         # Create an invalid libtool object if no PIC, so that we don't
         # accidentally link it into a program.
-        $show "$echo timestamp > $libobj"
-        $run eval "\$echo timestamp > $libobj" || exit $?
+        $show "echo timestamp > $libobj"
+        $run eval "echo timestamp > $libobj" || exit $?
         exit 0
       fi
 
@@ -1203,7 +1210,7 @@ if test -z "$show_help"; then
 	  if sort "$nlist" | uniq > "$nlist"T; then
 	    mv -f "$nlist"T "$nlist"
 	    wcout=`wc "$nlist" 2>/dev/null`
-	    count=`$echo "$wcout" | sed 's/^[ 	]*\([0-9][0-9]*\).*$/\1/'`
+	    count=`echo "$wcout" | sed 's/^[ 	]*\([0-9][0-9]*\).*$/\1/'`
 	    (test "$count" -ge 0) 2>/dev/null || count=-1
 	  else
 	    $rm "$nlist"T
@@ -1230,7 +1237,7 @@ EOF
 	    if test -f "$nlist"; then
 	      sed -e 's/^.* \(.*\)$/extern char \1;/' < "$nlist" >> "$objdir/$dlsyms"
 	    else
-	      $echo '/* NONE */' >> "$objdir/$dlsyms"
+	      echo '/* NONE */' >> "$objdir/$dlsyms"
 EOF
 	    fi
 
@@ -1258,7 +1265,7 @@ dld_preloaded_symbols[] =
 EOF
 
 	    if test -f "$nlist"; then
-	      sed 's/^\(.*\) \(.*\)$/  {"\1", \&\2},/' < "$nlist" >> "$objdir/$dlsyms"
+	      sed 's/^\(.*\) \(.*\)$/  {"\1", (__ptr_t) \&\2},/' < "$nlist" >> "$objdir/$dlsyms"
 	    fi
 
 	    cat <<\EOF >> "$objdir/$dlsyms"
@@ -1272,7 +1279,7 @@ EOF
 	    ;;
 
 	  *)
-	    echo "$progname: unknown suffix for \`$dlsyms'" 1>&2
+	    $echo "$progname: unknown suffix for \`$dlsyms'" 1>&2
 	    exit 1
 	    ;;
 	  esac
@@ -1475,7 +1482,7 @@ EOF
     # The program doesn't exist.
     \$echo "\$0: error: \$progdir/\$program does not exist" 1>&2
     \$echo "This script is just a wrapper for \$program." 1>&2
-    \$echo "See the $PACKAGE documentation for more information." 1>&2
+    echo "See the $PACKAGE documentation for more information." 1>&2
     exit 1
   fi
 fi
@@ -1995,11 +2002,11 @@ EOF
       done
     fi
 
-    $echo "To link against installed libraries in LIBDIR, users may have to:"
+    echo "To link against installed libraries in LIBDIR, users may have to:"
     if test -n "$shlibpath_var"; then
-      $echo "   - add LIBDIR to their \`$shlibpath_var' environment variable"
+      echo "   - add LIBDIR to their \`$shlibpath_var' environment variable"
     fi
-    $echo "   - use the \`-LLIBDIR' linker flag"
+    echo "   - use the \`-LLIBDIR' linker flag"
     exit 0
     ;;
 
@@ -2341,12 +2348,12 @@ a program from several object files.
 The following components of LINK-COMMAND are treated specially:
 
   -all-static       do not do any dynamic linking at all
-  -allow-undefined  allow a libtool library to reference undefined symbols
   -dlopen FILE      \`-dlpreopen' FILE if it cannot be dlopened at runtime
   -dlpreopen FILE   link in FILE and add its symbols to dld_preloaded_symbols
   -export-dynamic   allow symbols from OUTPUT-FILE to be resolved with dlsym(3)
   -LLIBDIR          search LIBDIR for required installed libraries
   -lNAME            OUTPUT-FILE requires the installed library libNAME
+  -no-undefined     declare that a library does not refer to external symbols
   -o OUTPUT-FILE    create OUTPUT-FILE from the specified objects
   -rpath LIBDIR     the created library will eventually be installed in LIBDIR
   -static           do not do any dynamic linking of libtool libraries
@@ -2392,7 +2399,7 @@ EOF
   ;;
 esac
 
-$echo
+echo
 $echo "Try \`$progname --help' for more information about other modes."
 
 exit 0
