bootstrap: update bootstrap script to latest upstream.
* bootstrap, build-aux/options-parser: apply upstream fixes and
enhancements.

Signed-off-by: Gary V. Vaughan <gary@gnu.org>

diff --git a/build-aux/options-parser b/build-aux/options-parser
--- a/build-aux/options-parser
+++ b/build-aux/options-parser
@@ -462,6 +462,9 @@ func_parse_options ()
       # Adjust func_parse_options positional parameters to match
       eval set dummy $func_run_hooks_result; shift
 
+      # Break out of the loop if we already parsed every option.
+      test $# -gt 0 || break
+
       _G_opt=$1
       shift
       case $_G_opt in
@@ -476,7 +479,7 @@ func_parse_options ()
         --help)       func_help ;;
 
 	# Separate optargs to long options (plugins may need this):
-	--*=*)        func_split_equals "$opt"
+	--*=*)        func_split_equals "$_G_opt"
 	              set dummy "$func_split_equals_lhs" \
                           "$func_split_equals_rhs" ${1+"$@"}
                       shift
@@ -587,24 +590,44 @@ func_echo ()
 }
 
 
-# func_error ARG...
-# -----------------
-# Echo program name prefixed message to standard error.
-func_error ()
+# func_echo_infix_1 INFIX ARG...
+# ------------------------------
+# Echo program name, followed by INFIX on the first line, with any
+# additional lines not showing INFIX.
+func_echo_infix_1 ()
 {
     $require_term_colors
 
+    _G_infix=$1; shift
+    _G_prefix="$progname: $tc_standout$tc_red$_G_infix$tc_reset: "
     _G_message=$*
-    _G_prefix="$progname: $tc_standout${tc_red}error$tc_reset: "
 
     save_IFS=$IFS
     IFS=$nl
     for _G_line in $_G_message; do
       IFS=$save_IFS
       $bs_echo "$_G_prefix$tc_bold$_G_line$tc_reset" 1>&2
-      _G_prefix="$progname:        "
+      _G_prefix="$progname: `echo $_G_infix | sed 's|.| |g'`  "
     done
     IFS=$save_IFS
+}
+
+
+# func_warn ARG...
+# ----------------
+# Echo program name (and 'warning') prefixed message to standard error.
+func_warn ()
+{
+    func_echo_infix_1 warning "$*"
+}
+
+
+# func_error ARG...
+# -----------------
+# Echo program name prefixed message to standard error.
+func_error ()
+{
+    func_echo_infix_1 error "$*"
 }
 
 
@@ -626,8 +649,8 @@ func_fatal_help ()
 {
     $debug_cmd
 
-    eval $bs_echo \""Usage: $usage"\"
-    eval $bs_echo \""$fatal_help"\"
+    eval \$bs_echo \""Usage: $usage"\"
+    eval \$bs_echo \""$fatal_help"\"
     func_error ${1+"$@"}
     exit $EXIT_FAILURE
 }
@@ -777,11 +800,11 @@ func_usage_message ()
 {
     $debug_cmd
 
-    eval $bs_echo \""$usage"\"
+    eval \$bs_echo \""$usage"\"
     echo
     $SED -n 's|^# ||;/^Written by/{x;p;x;};h' < "$progpath"
     echo
-    eval $bs_echo \""$usage_message"\"
+    eval \$bs_echo \""$usage_message"\"
 }
 
 
